### ISSUE TITLE
Ready for Grading Week 2 Assignment

### ISSUE THREAD

**Issue by ndaley-matc** [madisoncollege-it-programs/python-scripting-ndaley-matc#1]
I think I did this right.  It was week 2 so I labeled the folder as such.

**Comment by cethenmc** [comment]
Hi, Nathan - Assignment #1 for week2 is good.  For Assignment #2, I would like you to update your script so you can run it from the command line.

Your first line should always be the following for your scripts. In this way, if you are running from the command line it will know what interpreter to use. Will you please add this line to the top of your first-script.py code?  You were close.

#!/usr/bin/env python3

Recall from the videos, you may also need to issue a chmod command to modify the rights to make it executable.

chmod u+x first-script.py

After this, you can execute from the command line.

./first-script.py

Please be so kind as to resubmit it, so...
    1. modify the file in NetLab with the added line at the top.
    2. update the file to be executable.
    3. add the file to staging (git add .)
    4. commit the file to your local repo. (git commit -m "changes requested to run from command line")
    5. push to the git hub repository (git push)
    6. reply to this same issue, saying you have completed these steps

Thanks.

~Chris

**Comment by ndaley-matc** [comment]
Chris, 

Thank you for the heads and direction.  I should have the changes in place you requested.

**Comment by cethenmc** [comment]
looks good!  Thanks!
