### ISSUE TITLE
Week 10 ready for Grading

### ISSUE THREAD

**Issue by ndaley-matc** [madisoncollege-it-programs/python-scripting-ndaley-matc#12]
Ready for review.

**Comment by cethenmc** [comment]
Hi Nathan.  You can resubmit for full credit.

Recorded as a 4 of 8 for now.

myProcString and myProcList.  No for loop.  And the list was supposed to look similar to the way it would look if you ran the command directly in the terminal.

Thanks.

**Comment by ndaley-matc** [comment]
I should have the loop you were looking for in the script.  As far as I can tell it is printing just like as I had typed the command "ps -axco command".  If I'm missing something please let me know.  Thank you.

**Comment by cethenmc** [comment]
Hi, Nathan.  I just did a git pull, and I don't see anything new for Week10.  Are you sure you pushed your changes to the git hub?

**Comment by ndaley-matc** [comment]
Cathie,   So sorry.  I thought I did, but it was showing red when I checked in the "git-status".  So I just did a push with it now.

**Comment by cethenmc** [comment]
Thanks.  I will check it out.  Cathie is the one presenting in the videos.  However, my name is Chris😊  I think you know that😊

Chris

[signature_146958654]
Chris Ethen | Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by ndaley-matc** [comment]
Resubmitted for grading.

**Comment by cethenmc** [comment]
Please ignore my last comment.  It is there and looks good!  I had modified the file when grading, so it did not pull down initially.


Chris

[signature_146958654]
Chris Ethen | Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>


From: Ethen, Christopher M
Sent: Wednesday, November 23, 2022 11:28 AM
To: 'madisoncollege-it-programs/python-scripting-ndaley-matc' ***@***.***>; madisoncollege-it-programs/python-scripting-ndaley-matc ***@***.***>
Cc: Comment ***@***.***>
Subject: RE: [madisoncollege-it-programs/python-scripting-ndaley-matc] Week 10 ready for Grading (Issue #12)

I see Week 11 coming down.  However, I do not see week 10 coming down from GitHub.  What I currently have is not the final product we worked on.

Chris

[signature_146958654]
Chris Ethen | Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by cethenmc** [comment]
Full credit.  Closing ticket.
