### ISSUE TITLE
Final-Exam Ready for Grading

### ISSUE THREAD

**Issue by ndaley-matc** [madisoncollege-it-programs/python-scripting-ndaley-matc#18]
Final ready to be graded.

**Comment by cethenmc** [comment]
Nathan - The lack of functions was a killer on this final.  I did, however, take note of everything you did, and you squeaked a 77 out of it.  With that 77, you managed to edge into an AB.  If you continue using Python, I highly recommend revisiting functions.  You should have shown you could demonstrate them, but you did not define a single function on the Final Project.  I wish you the best and am grateful I was able to work with you some this semester.

![image](https://user-images.githubusercontent.com/112707666/207774620-3b50eb96-7ee2-4012-8a36-472468e321f6.png)

Best wishes!

Chris
