### ISSUE TITLE
Week 3 Assignment Ready to grade

### ISSUE THREAD

**Issue by ndaley-matc** [madisoncollege-it-programs/python-scripting-ndaley-matc#2]
I got all the outputs to match as directed.

**Comment by cethenmc** [comment]
I was going to let this slide, but I think you want 100%.  Fix #13 (it should use some of #12 except instead of dollar signs, use spaces.  Then add your slicing to the end of the formatted string for red and blue.

Then, since you are in there, please fix your spelling issue in #14.

**Comment by cethenmc** [comment]
Unfortunately, it is not showing correctly.  However, you got the most important part.  Nice work!  Full credit.
