### ISSUE TITLE
Week 4 ready for grading

### ISSUE THREAD

**Issue by ndaley-matc** [madisoncollege-it-programs/python-scripting-ndaley-matc#3]
Thank you

**Comment by cethenmc** [comment]
Fix #6 and resubmit.  If you prefer I take the grade as is, then let me know.  Personally, I would like to see you get 100%.  ~Chris

**Comment by ndaley-matc** [comment]
I'm not seeing a #6.  It looks like the assignment ended on #5 asking to use a loop to print out each element of the varList one line at a time.

**Comment by cethenmc** [comment]
Very sorry.  #6 is really #3(a).  It ends up being the 6th line that prints.

**Comment by ndaley-matc** [comment]
Ahh.  I have made the adjust as asked.  Should be all good.

**Comment by cethenmc** [comment]
Looks much better!  Thank you!
