### ISSUE TITLE
Week 6 Part 2 (Flowcontrol) Ready for grading

### ISSUE THREAD

**Issue by ndaley-matc** [madisoncollege-it-programs/python-scripting-ndaley-matc#6]

**Comment by ndaley-matc** [comment]
Week 6 flowcontrol ready for grading.

**Comment by ndaley-matc** [comment]
Chris, 

I will make sure to test from the command line prior to submission.  I have made the changes.  Thanks for the heads up.

-Nathan

**Comment by cethenmc** [comment]
Hi, Nathan.  I don't see that this was pushed to GitHub yet.

**Comment by cethenmc** [comment]
when I try to pull

student@python-client:~/Repo/Online/python-scripting-ndaley-matc$ git pull
**Already up to date.**

This means your changes were not sent to GitHub.

**Comment by ndaley-matc** [comment]
I am so sorry.  I forgot all about the push to GitHub.  I was really focused on doing the chmod and forgot I need to update the repository.  It should be pushed now.

**Comment by cethenmc** [comment]
Hi, Nathan.  Please see my note for the boolean assignment this week.  They are the same issue.  Thanks.  ~Chris

**Comment by cethenmc** [comment]
Thanks for making executable now.  You fulfilled the requirement for this lesson.
